# Generated by Django 6.0.2 on 2026-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('delivery', 'Delivery')], default='customer', max_length=20),
        ),
    ]
